### ISSUE TITLE
sql error in admin panel page

### ISSUE THREAD

**Issue by blitz2150** [qahar/oc-image-auto-resize#1]
hi.
I used this vqmod it’s great and works fine. but i get error in the admin panel page.
just admin panel page, other pages are fine
Notice: Error: FUNCTION opencartasli.pyear does not exist
Error No: 1305
SELECT SUM(total) AS total FROM `oc_order` WHERE order_status_id > ’0′ AND pyear(date_added) = ’1394′ in C:\wamp\www\opencart asli\system\database\mysql.php on line 50

**Comment by qahar** [comment]
Hi,

Your error is not related to Image Auto Resize, I suggest you to post at http://forum.opencart.com/
